performance updates, added a tail pointer to sessionslist code

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1262,6 +1262,8 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
+  --enable-debug=no/yes turn on debugging
+                       default=$debug_default
 
 Some influential environment variables:
   CC          C compiler command
@@ -2037,7 +2039,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=nfex
- VERSION=2.4
+ VERSION=2.5
 
 
 cat >>confdefs.h <<_ACEOF
@@ -2269,7 +2271,7 @@ case $host_os in *\ *) host_os=`echo "$host_os" | sed 's/ /-/g'`;; esac
 ac_config_headers="$ac_config_headers include/config.h"
 
 
-CFLAGS="$CFLAGS"
+CFLAGS="$CFLAGS -ggdb"
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -3857,6 +3859,25 @@ else
 fi
 
 
+{ echo "$as_me:$LINENO: checking whether to enable debugging" >&5
+echo $ECHO_N "checking whether to enable debugging... $ECHO_C" >&6; }
+debug_default="no"
+# Check whether --enable-debug was given.
+if test "${enable_debug+set}" = set; then
+  enableval=$enable_debug;
+else
+  enable_debug=$debug_default
+fi
+
+if test "x$enable_debug" = "xyes"; then
+         CFLAGS="$CFLAGS -ggdb -DDEBUG_MODE"
+{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
 
 { echo "$as_me:$LINENO: checking for main in -lfl" >&5
 echo $ECHO_N "checking for main in -lfl... $ECHO_C" >&6; }
@@ -4168,6 +4189,94 @@ echo "${ECHO_T}$ac_cv_search_floor" >&6; }
 ac_res=$ac_cv_search_floor
 if test "$ac_res" != no; then
   test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+fi
+
+{ echo "$as_me:$LINENO: checking for library containing event_base_new" >&5
+echo $ECHO_N "checking for library containing event_base_new... $ECHO_C" >&6; }
+if test "${ac_cv_search_event_base_new+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char event_base_new ();
+int
+main ()
+{
+return event_base_new ();
+  ;
+  return 0;
+}
+_ACEOF
+for ac_lib in '' event; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_search_event_base_new=$ac_res
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext
+  if test "${ac_cv_search_event_base_new+set}" = set; then
+  break
+fi
+done
+if test "${ac_cv_search_event_base_new+set}" = set; then
+  :
+else
+  ac_cv_search_event_base_new=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_event_base_new" >&5
+echo "${ECHO_T}$ac_cv_search_event_base_new" >&6; }
+ac_res=$ac_cv_search_event_base_new
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+  have_libevent=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBEVENT 1
+_ACEOF
 
 fi
 
