more odds and ends

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -2037,7 +2037,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=nfex
- VERSION=2.3
+ VERSION=2.4
 
 
 cat >>confdefs.h <<_ACEOF
@@ -2269,7 +2269,7 @@ case $host_os in *\ *) host_os=`echo "$host_os" | sed 's/ /-/g'`;; esac
 ac_config_headers="$ac_config_headers include/config.h"
 
 
-CFLAGS="$CFLAGS -ggdb"
+CFLAGS="$CFLAGS"
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -4000,6 +4000,89 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_search_pcap_open_live" >&5
 echo "${ECHO_T}$ac_cv_search_pcap_open_live" >&6; }
 ac_res=$ac_cv_search_pcap_open_live
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+fi
+
+{ echo "$as_me:$LINENO: checking for library containing libnet_init" >&5
+echo $ECHO_N "checking for library containing libnet_init... $ECHO_C" >&6; }
+if test "${ac_cv_search_libnet_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char libnet_init ();
+int
+main ()
+{
+return libnet_init ();
+  ;
+  return 0;
+}
+_ACEOF
+for ac_lib in '' net; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_search_libnet_init=$ac_res
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext
+  if test "${ac_cv_search_libnet_init+set}" = set; then
+  break
+fi
+done
+if test "${ac_cv_search_libnet_init+set}" = set; then
+  :
+else
+  ac_cv_search_libnet_init=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_libnet_init" >&5
+echo "${ECHO_T}$ac_cv_search_libnet_init" >&6; }
+ac_res=$ac_cv_search_libnet_init
 if test "$ac_res" != no; then
   test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
 
